### PR TITLE
Add transform tests

### PR DESCRIPTION
**Pull request by mbostock**
Supersedes #38.

- [ ] Revert change to package.json.
- [ ] Use double quotes instead of single quotes in test for strings.

### CODE REVIEW

**Comment by mbostock** [comment]
My mistake I told you to do the opposite of what I wanted. I meant to adopt double quotes for the strings… Sorry!

**Comment by TrySound** [comment]
You may create `eslint-config-d3` :)

**Comment by mbostock** [comment]
Test looks good now, but I’d still like you to revert the change to the package.json. The double quotes mean that the argument is still expanded by the shell, and I don’t want to enable eslint for the test directory (yet). The eslint enhancement is nice but I’d want to make it across all the D3 repos simultaneously.

**Comment by TrySound** [comment]
Which shell evaluates double quoted globs? It doesn't make sense.

**Comment by mbostock** [comment]
Well, Bash evaluates variables (`${FOO}`) within double-quoted strings. It doesn’t expand globs, though, so I guess it would be fine.

Please revert the change to the .eslintrc. I’ll consider applying that across all the D3 modules simultaneously separate from the new test. Thank you!

**Comment by TrySound** [comment]
Then let's keep globs double quoted to reduce pain on windows.

**Comment by TrySound** [comment]
Or you want do that simultaneously?

**Comment by mbostock** [comment]
I’m pretty sure I had double-quoted args before and there was an issue with it, so I’m hesitant to change things without testing.

**Comment by mbostock** [comment]
Thanks for the tests!

**Pull request merged**
