### PR TITLE
Emit end event after last zoom which had an effect

### PR DESCRIPTION
**Pull request by Herst**
See #158

### CODE REVIEW

**Comment by Herst** [comment]
@mbostock That ought do it and not break anything, right? Because the stored mouse location plays no role in those cases where the wheel event wouldn't make any difference (e.g. because of the `scaleExtent`).

**Comment by mbostock** [comment]
This looks correct to me. The new `else` is redundant (because of the preceding `return`).

**Comment by Herst** [comment]
Fixed.

**Comment by mbostock** [comment]
Merged as f4c6c792a26a6293a3e43911f2117e28852329c2.

**Pull request closed without merging**
